name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    #- uses: actions/cache@v3
    #  with:
    #    path: |
    #      ~/.cargo/bin/
    #      ~/.cargo/registry/index/
    #      ~/.cargo/registry/cache/
    #      ~/.cargo/git/db/
    #      target/
    #    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install libosmesa6-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo test --verbose

  package:
    needs: [build]
    name: Package
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Cargo Deb
      run: cargo install cargo-deb
    - name: Package
      run: cargo deb
    - uses: actions/upload-artifact@v3
      with:
        name: ubuntu-18.04-package
        path: target/debian/*.deb
