name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-buildtest-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install libosmesa6-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo test --verbose

  package:
    needs: [build]
    name: Package
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, aarch64-unknown-linux-gnu]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu libc-dev-armhf-cross libc-dev-arm64-cross
    - name: Prep build environment
      run: |
        rustup target add ${{ matrix.target }}
        cargo install cargo-deb
    - name: Package
      run: cargo deb --target ${{ matrix.target }}
    - uses: actions/upload-artifact@v3
      with:
        name: deb-${{ matrix.target }}
        path: target/${{ matrix.target }}/debian/*.deb
